[package]
name = "openlink-pod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tokio = { version = "1.15.0", features = ["full"] }
bincode = "1.3.3"
log = { version = "0.4", features = ["std"] }
mio = "0.6"
quiche = "0.10.0"
ring = "0.16"
serde = { version = "1.0.133", features = ["derive"] }
unqlite = "1.3.0"
